---
- name: Set awscli facts
  tags:
    - awscli
  set_fact:
    awscli_package_url: https://awscli.amazonaws.com/awscli-exe-{{ ansible_facts.system|lower }}-{{ ansible_facts.machine }}.zip
    awscli_temp_dest: "{{ awscli_temp_dir|default('/tmp', true) }}/aws"

- name: Test awscli installed
  tags:
    - awscli
  command:
    cmd: which aws
  register: aws_location
  changed_when: aws_location.rc == 1
  failed_when: False

- when: aws_location.changed
  tags:
    - awscli
  block:
    - name: Download awscli installer
      unarchive:
        src: "{{ awscli_package_url }}"
        dest: "{{ awscli_temp_dir|default('/tmp', true) }}"
        remote_src: yes
        creates: "{{ awscli_temp_dest }}"
        mode: 0755

    - name: Run awscli installer
      become: true
      command:
      args:
        cmd: "{{ awscli_temp_dest }}/install"
        creates: /usr/local/bin/aws

    - name: Clean up awscli installer
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - "{{ awscli_temp_dest }}"

- name: Ensure awscli config directory
  tags:
    - awscli
  file:
    path: "{{ awscli_config_dir }}"
    state: directory
    owner: "{{ awscli_user }}"
    group: "{{ awscli_user }}"
    mode: "700"

- name: Template awscli config files
  when: awscli_profiles is defined
  tags:
    - awscli
  template:
    src: templates/{{ item }}.j2
    dest: "{{ awscli_config_dir }}/{{ item }}"
    owner: "{{ awscli_user }}"
    group: "{{ awscli_user }}"
    mode: "600"
  loop:
    - config
    - credentials
