---
- name: Test awscli installed
  command:
    cmd: which aws
  register: aws_location
  changed_when: aws_location.rc == 1
  failed_when: False

- when: aws_location.changed
  block:
    - name: Set awscli install variables
      set_fact:
        awscli_package_url: https://awscli.amazonaws.com/awscli-exe-{{ ansible_facts['ansible_system']|lower }}-{{ ansible_facts['ansible_machine'] }}.zip
        awscli_temp_dest: "{{ (awscli_temp_dir, 'aws')|path_join }}"

    - name: Download awscliv2 installer.
      unarchive:
        src: "{{ awscli_package_url }}"
        dest: "{{ awscli_temp_dir }}"
        remote_src: yes
        creates: "{{ awscli_temp_dest }}"
        mode: 0755

    - name: Run the installer.
      become: true
      command:
      args:
        cmd: "{{ (awscli_temp_dest, 'install')|path_join }}"
        creates: /usr/local/bin/aws
